spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #druid监控页的配置
    druid:
      #开启Web监控&防火墙功能
      filters: stat,wall
      #单独详细配置
      filter:
        stat:
          #慢查询
          slow-sql-millis: 1000
          #日志是否记录慢查询
          log-slow-sql: true
        wall:
          enabled: true

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      #监控web应用
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #排除
        exclusions: '*.gif,*.js,*.jpg,*.png,*.css,*.ico,/druid/*'
      #监控springBean
      aop-patterns: com.atguigu.admin.*
  jdbc:
    template:
      query-timeout: 3
mybatis:

  #config-location: classpath:mybatis/mybatis-config.xml
  #Property 'configuration' and 'configLocation' can not specified with together
  #sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true